/* SLIDESITEMS */
export const GET_SLIDESITEMS = "GET_SLIDESITEMS"
export const GET_SLIDESITEMS_SUCCESS = "GET_SLIDESITEMS_SUCCESS"
export const GET_SLIDESITEMS_FAIL = "GET_SLIDESITEMS_FAIL"


/**
 * add category
 */
export const ADD_NEW_SLIDESITEM = "ADD_NEW_SLIDESITEM"
export const ADD_SLIDESITEM_SUCCESS = "ADD_SLIDESITEM_SUCCESS"
export const ADD_SLIDESITEM_FAIL = "ADD_SLIDESITEM_FAIL"

/**
 * Edit category
 */
export const UPDATE_SLIDESITEM = "UPDATE_SLIDESITEM"
export const UPDATE_SLIDESITEM_SUCCESS = "UPDATE_SLIDESITEM_SUCCESS"
export const UPDATE_SLIDESITEM_FAIL = "UPDATE_SLIDESITEM_FAIL"

/**
 * Delete category
 */
export const DELETE_SLIDESITEM = "DELETE_SLIDESITEM"
export const DELETE_SLIDESITEM_SUCCESS = "DELETE_SLIDESITEM_SUCCESS"
export const DELETE_SLIDESITEM_FAIL = "DELETE_SLIDESITEM_FAIL"
