/* PATTRIBUTEITEMS */
export const GET_PATTRIBUTEITEMS = "GET_PATTRIBUTEITEMS"
export const GET_PATTRIBUTEITEMS_SUCCESS = "GET_PATTRIBUTEITEMS_SUCCESS"
export const GET_PATTRIBUTEITEMS_FAIL = "GET_PATTRIBUTEITEMS_FAIL"


/**
 * add category
 */
export const ADD_NEW_PATTRIBUTEITEM = "ADD_NEW_PATTRIBUTEITEM"
export const ADD_PATTRIBUTEITEM_SUCCESS = "ADD_PATTRIBUTEITEM_SUCCESS"
export const ADD_PATTRIBUTEITEM_FAIL = "ADD_PATTRIBUTEITEM_FAIL"

/**
 * Edit category
 */
export const UPDATE_PATTRIBUTEITEM = "UPDATE_PATTRIBUTEITEM"
export const UPDATE_PATTRIBUTEITEM_SUCCESS = "UPDATE_PATTRIBUTEITEM_SUCCESS"
export const UPDATE_PATTRIBUTEITEM_FAIL = "UPDATE_PATTRIBUTEITEM_FAIL"

/**
 * Delete category
 */
export const DELETE_PATTRIBUTEITEM = "DELETE_PATTRIBUTEITEM"
export const DELETE_PATTRIBUTEITEM_SUCCESS = "DELETE_PATTRIBUTEITEM_SUCCESS"
export const DELETE_PATTRIBUTEITEM_FAIL = "DELETE_PATTRIBUTEITEM_FAIL"
