/* PVARIATIONS */
export const GET_PVARIATIONS = "GET_PVARIATIONS"
export const GET_PVARIATIONS_SUCCESS = "GET_PVARIATIONS_SUCCESS"
export const GET_PVARIATIONS_FAIL = "GET_PVARIATIONS_FAIL"


/**
 * add category
 */
export const ADD_NEW_PVARIATION = "ADD_NEW_PVARIATION"
export const ADD_PVARIATION_SUCCESS = "ADD_PVARIATION_SUCCESS"
export const ADD_PVARIATION_FAIL = "ADD_PVARIATION_FAIL"

/**
 * Edit category
 */
export const UPDATE_PVARIATION = "UPDATE_PVARIATION"
export const UPDATE_PVARIATION_SUCCESS = "UPDATE_PVARIATION_SUCCESS"
export const UPDATE_PVARIATION_FAIL = "UPDATE_PVARIATION_FAIL"

/**
 * Delete category
 */
export const DELETE_PVARIATION = "DELETE_PVARIATION"
export const DELETE_PVARIATION_SUCCESS = "DELETE_PVARIATION_SUCCESS"
export const DELETE_PVARIATION_FAIL = "DELETE_PVARIATION_FAIL"


export const SET_PVARIATION_SUCCESS = "SET_PVARIATION_SUCCESS"
