/* PATTRIBUTES */
export const GET_PATTRIBUTES = "GET_PATTRIBUTES"
export const GET_PATTRIBUTES_SUCCESS = "GET_PATTRIBUTES_SUCCESS"
export const GET_PATTRIBUTES_FAIL = "GET_PATTRIBUTES_FAIL"


/**
 * add category
 */
export const ADD_NEW_PATTRIBUTE = "ADD_NEW_PATTRIBUTE"
export const ADD_PATTRIBUTE_SUCCESS = "ADD_PATTRIBUTE_SUCCESS"
export const ADD_PATTRIBUTE_FAIL = "ADD_PATTRIBUTE_FAIL"

/**
 * Edit category
 */
export const UPDATE_PATTRIBUTE = "UPDATE_PATTRIBUTE"
export const UPDATE_PATTRIBUTE_SUCCESS = "UPDATE_PATTRIBUTE_SUCCESS"
export const UPDATE_PATTRIBUTE_FAIL = "UPDATE_PATTRIBUTE_FAIL"

/**
 * Delete category
 */
export const DELETE_PATTRIBUTE = "DELETE_PATTRIBUTE"
export const DELETE_PATTRIBUTE_SUCCESS = "DELETE_PATTRIBUTE_SUCCESS"
export const DELETE_PATTRIBUTE_FAIL = "DELETE_PATTRIBUTE_FAIL"
