/* PVARIATIONATTRIBUTES */
export const GET_PVARIATIONATTRIBUTES = "GET_PVARIATIONATTRIBUTES"
export const GET_PVARIATIONATTRIBUTES_SUCCESS = "GET_PVARIATIONATTRIBUTES_SUCCESS"
export const GET_PVARIATIONATTRIBUTES_FAIL = "GET_PVARIATIONATTRIBUTES_FAIL"


/**
 * add category
 */
export const ADD_NEW_PVARIATIONATTRIBUTE = "ADD_NEW_PVARIATIONATTRIBUTE"
export const ADD_PVARIATIONATTRIBUTE_SUCCESS = "ADD_PVARIATIONATTRIBUTE_SUCCESS"
export const ADD_PVARIATIONATTRIBUTE_FAIL = "ADD_PVARIATIONATTRIBUTE_FAIL"

/**
 * Edit category
 */
export const UPDATE_PVARIATIONATTRIBUTE = "UPDATE_PVARIATIONATTRIBUTE"
export const UPDATE_PVARIATIONATTRIBUTE_SUCCESS = "UPDATE_PVARIATIONATTRIBUTE_SUCCESS"
export const UPDATE_PVARIATIONATTRIBUTE_FAIL = "UPDATE_PVARIATIONATTRIBUTE_FAIL"

/**
 * Delete category
 */
export const DELETE_PVARIATIONATTRIBUTE = "DELETE_PVARIATIONATTRIBUTE"
export const DELETE_PVARIATIONATTRIBUTE_SUCCESS = "DELETE_PVARIATIONATTRIBUTE_SUCCESS"
export const DELETE_PVARIATIONATTRIBUTE_FAIL = "DELETE_PVARIATIONATTRIBUTE_FAIL"
